defmodule Pubsub.HtmlSubscriber do
  @moduledoc """
  Subscriber that formats articles as HTML.
  """

  use GenServer
  require Logger

  def start_link(_opts) do
    GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  end

  @impl true
  def init(state) do
    Logger.info("HTML Subscriber started")
    Pubsub.EventBus.subscribe(:article_published)
    {:ok, state}
  end

  @impl true
  def handle_info({:event, :article_published, article}, state) do
    Logger.info("HTML Subscriber received article: #{article.title}")
    html_content = format_as_html(article)

    File.write!("article_#{article.id}_html.html", html_content)
    Logger.info("Article formatted as HTML and saved to article_#{article.id}_html.html")

    {:noreply, state}
  end

  defp format_as_html(article) do
    """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>#{html_escape(article.title)}</title>
        <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
            .article-header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
            .article-meta { color: #666; font-size: 0.9em; }
            .article-content { line-height: 1.6; margin: 20px 0; }
            .footer { border-top: 1px solid #ccc; margin-top: 30px; padding-top: 10px; font-style: italic; }
        </style>
    </head>
    <body>
        <div class="article-header">
            <h1>#{html_escape(article.title)}</h1>
            <div class="article-meta">
                <strong>Author:</strong> #{html_escape(article.author)}<br>
                <strong>Published:</strong> #{DateTime.to_string(article.published_at)}<br>
                <strong>ID:</strong> #{html_escape(article.id)}
            </div>
        </div>

        <div class="article-content">
            <p>#{html_escape(article.content)}</p>
        </div>

        <div class="footer">
            <p><em>Generated by HTML Subscriber</em></p>
        </div>
    </body>
    </html>
    """
  end

  defp html_escape(text) do
    text
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
    |> String.replace("'", "&#39;")
  end
end
